### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by jcfr** [thewtex/docker-centos-build#2]
Makefile should allow to build and push

Example: https://github.com/jcfr/dockgit-rocket-filter/blob/master/Makefile

**Comment by jcfr** [comment]
Cc: @MayeulChassagnard

**Comment by MayeulChassagnard** [comment]
I am currently trying to build the docker image without success because of this remaining error with:
* `wget`:
![wget_error](https://cloud.githubusercontent.com/assets/20341270/19356098/9b5eb7d6-913a-11e6-91e8-5212063bc734.png)
* `curl`:
![curl_error35](https://cloud.githubusercontent.com/assets/20341270/19356096/98158b7c-913a-11e6-859d-e1e461741def.png)

And I also verified:
```
openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

curl --version
curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
Protocols: tftp ftp telnet dict ldap http file https ftps 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz 

wget --version
GNU Wget 1.11.4 Red Hat modified
Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Currently maintained by Micah Cowan <micah@cowan.name>.
```

See the commit about the [makefile & update of Libtool](https://github.com/MayeulChassagnard/docker-centos-build/commit/19d5af4eeeacfc317cf8148713f26cebfac0b0dd) #3

**Comment by jcfr** [comment]
To unblock and move forward, download the archives outside of docker with a
script. You can then use COPY instruction to copy the archive in docker

**Comment by MayeulChassagnard** [comment]
[Solved](https://github.com/MayeulChassagnard/docker-centos-build/commit/b8efbbbef13521b421545e26d96fbb070ae1a65b)

**Comment by jcfr** [comment]
Closing. This will be added by #11
